### ISSUE TITLE
XTC - Test failure

### ISSUE THREAD

**Issue by Reedyuk** [xamarinhq/test-cloud-appium-java-extensions#10] opened 2017-03-22 14:38 UTC
Hi, I have downloaded the latest xtc and ran the command to upload/test but i seem to be getting this error:
https://gist.github.com/Reedyuk/e0a91eecdaeb45843c6ca12394567306

Any help? I'm not sure why it is complaining about too many open files, this project is fairly big so it could be why?

Thanks
Andrew.

**Comment by Reedyuk** [comment] 2017-03-28 07:34
![giphy](https://cloud.githubusercontent.com/assets/3853006/24393785/58828206-1391-11e7-8caa-dc84958d328c.gif)

**Comment by john7doe** [comment] 2017-04-07 14:13
Andrew,

We been so busy working on [Visual Studio Mobile Center](https://www.visualstudio.com/vs/mobile-center/) 
![](https://media.giphy.com/media/XIqCQx02E1U9W/giphy.gif)

That your issue slipped under our radar. Many apologies for that. 

We will take a look at the issue soon. One of the things that kept us busy was a new an improved CLI, hopefully it will be better at coping with the many files in your project. So if you visit this [link](https://docs.microsoft.com/en-us/mobile-center/test-cloud/getting-started) you will find instructions on using the new CLI to upload tests.

Br,
/Simon

**Comment by Reedyuk** [comment] 2017-04-07 14:17
Thanks Simon, i will have a look.

**Comment by FranMartinRomero** [comment] 2017-05-15 14:10
Hi guys, any update for this issue?

**Comment by john7doe** [comment] 2017-06-08 07:42
@Reedyuk and @FranMartinRomero I've been unable to reproduce the bug. I'm suspecting that it might be an error in the CoreCLR project (https://github.com/dotnet/corefx/issues/7932), so I have updated the project to use version 1.04 of CoreCLR where the bug should be fixed.

Please download the latest build following the instructions here: https://github.com/xamarinhq/test-cloud-uploader#installation and use this version for uploading

**Closed by john7doe** 2017-06-08 07:42 UTC

**Comment by FranMartinRomero** [comment] 2017-06-08 14:24
Thanks @john7doe we will try again.
